# Generated by Django 5.2.4 on 2025-07-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('adresse', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='form',
            name='statut',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('simple', 'Simple'), ('admin', 'Admin'), ('super_admin', 'Super_admin')], max_length=100),
        ),
    ]
