# Generated by Django 5.2.4 on 2025-07-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_form_background_color_remove_form_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
