# Generated by Django 5.2.4 on 2025-07-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_categorie_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='label',
        ),
        migrations.AddField(
            model_name='form',
            name='link',
            field=models.CharField(default='f', max_length=100),
            preserve_default=False,
        ),
    ]
