# Generated by Django 5.2.4 on 2025-07-26 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_categorie_code_uid_choices_code_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='creator',
        ),
    ]
