# Generated by Django 5.2.4 on 2025-07-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_remove_form_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='statut',
            field=models.BooleanField(default=False),
        ),
    ]
