# Generated by Django 5.2.4 on 2025-07-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_remove_reponse_reponse_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
