# Generated by Django 5.2.4 on 2025-07-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_form_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='cat_form',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
