# Generated by Django 5.2.4 on 2025-07-27 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_alter_question_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReponseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('user', models.CharField(max_length=100)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.form')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
