# Generated by Django 5.2.4 on 2025-07-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_alter_reponse_user_alter_reponseuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponse',
            name='form',
            field=models.CharField(default='10', max_length=50),
            preserve_default=False,
        ),
    ]
