# Generated by Django 5.2.4 on 2025-07-30 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_formulaire_cree_par'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='sous_section',
        ),
        migrations.RenameField(
            model_name='formulaire',
            old_name='created_at',
            new_name='date_creation',
        ),
        migrations.RemoveField(
            model_name='formulaire',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='question',
            name='obligatoire',
        ),
        migrations.RemoveField(
            model_name='section',
            name='ordre',
        ),
        migrations.AddField(
            model_name='formulaire',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='formulaires', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_sections', to='quiz.section'),
        ),
        migrations.AlterField(
            model_name='question',
            name='texte',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='SousSection',
        ),
    ]
