# Generated by Django 5.2.4 on 2025-07-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_terminal_form_statut_alter_user_type_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='form',
            name='code',
        ),
    ]
