# Generated by Django 5.2.4 on 2025-07-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_question_sous_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire',
            name='etat',
            field=models.BooleanField(default=False),
        ),
    ]
