# Generated by Django 5.2.4 on 2025-07-26 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_rename_question_question_label_form_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='choice',
            new_name='option',
        ),
    ]
