# Generated by Django 5.2.4 on 2025-07-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_rename_choice_choices_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='code_uid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='choices',
            name='code_uid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='code_uid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
