# Generated by Django 5.2.4 on 2025-07-26 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_form_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='link',
        ),
    ]
