# Generated by Django 5.2.4 on 2025-07-26 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_remove_form_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReponseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('rep', models.CharField(max_length=150)),
                ('user', models.CharField(max_length=100)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.categorie')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('user', models.CharField(max_length=100)),
                ('formulaire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.form')),
                ('reponse_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.reponsequestion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
