# Generated by Django 5.2.4 on 2025-07-26 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_reponsequestion_reponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponse',
            name='reponse_question',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='formulaire',
        ),
        migrations.AddField(
            model_name='reponse',
            name='question',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reponse',
            name='rep',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.DeleteModel(
            name='ReponseQuestion',
        ),
    ]
