# Generated by Django 5.2.4 on 2025-07-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_reponse_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponse',
            name='form',
        ),
    ]
