# Generated by Django 5.2.4 on 2025-07-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_remove_reponse_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='model',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
