# Generated by Django 5.2.4 on 2025-07-29 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_terminal_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
