# Generated by Django 5.2.4 on 2025-07-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_remove_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adresse',
        ),
    ]
