# Generated by Django 5.2.4 on 2025-07-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_authorizeddevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorizedDevice',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='model',
        ),
        migrations.AddField(
            model_name='terminal',
            name='device_name',
            field=models.CharField(default='hu', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terminal',
            name='device_uuid',
            field=models.CharField(default='nbbyvyvyv', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terminal',
            name='fingerprint',
            field=models.CharField(default='hvuuvtguu', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='terminal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
